"use client";

import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import { getRoleDashboardPath, getVerifiedTotpFactors, sanitizeInternalReturnPath, type VerifiedTotpFactor } from "@/lib/mfa";
import type { WebUserRole } from "@/lib/role-redirect";
import { supabase } from "@/lib/supabase";

type Profile = { role: WebUserRole; is_active: boolean | null };

function VerifyMfaPageContent() {
  const router = useRouter(); const searchParams = useSearchParams(); const [factors, setFactors] = useState<VerifiedTotpFactor[]>([]); const [selected, setSelected] = useState(""); const [code, setCode] = useState(""); const [role, setRole] = useState<WebUserRole | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const destination = role ? sanitizeInternalReturnPath(searchParams.get("returnTo"), getRoleDashboardPath(role)) : "/login";
  useEffect(() => { let active = true; async function load() { const { data: session } = await supabase.auth.getSession(); if (!session.session) { router.replace("/login"); return; } const { data: userData } = await supabase.auth.getUser(); if (!userData.user) { router.replace("/login"); return; } const { data: profile } = await supabase.from("profiles").select("role, is_active").eq("profile_id", userData.user.id).maybeSingle<Profile>(); if (!profile || profile.is_active !== true || (profile.role !== "admin" && profile.role !== "administrator" && profile.role !== "dispatcher")) { router.replace("/login"); return; } const { data: aal } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel(); const { data: factorData, error: factorError } = await supabase.auth.mfa.listFactors(); if (!active) return; setRole(profile.role); if (aal?.currentLevel === "aal2") { router.replace(sanitizeInternalReturnPath(searchParams.get("returnTo"), getRoleDashboardPath(profile.role))); return; } const verified = factorError ? [] : getVerifiedTotpFactors(factorData); if (!verified.length || aal?.nextLevel !== "aal2") { setError("No verified authenticator is available for this session."); } else { setFactors(verified); setSelected(verified[0].id); } setLoading(false); } void load(); return () => { active = false; }; }, [router, searchParams]);
  async function verify() { if (!selected || !/^\d{6}$/.test(code) || busy) { setError("Enter a six-digit authenticator code."); return; } setBusy(true); setError(""); const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({ factorId: selected }); if (challengeError || !challenge) { setError("Authenticator verification could not be started. Try again."); setBusy(false); return; } const { error: verifyError } = await supabase.auth.mfa.verify({ factorId: selected, challengeId: challenge.id, code }); if (verifyError) { setCode(""); setError("The authenticator code could not be verified. Try again."); setBusy(false); return; } const { data: aal } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel(); if (aal?.currentLevel !== "aal2") { setError("Authenticator verification could not be confirmed. Try again."); setBusy(false); return; } router.replace(destination); }
  async function signOut() { setBusy(true); await supabase.auth.signOut(); router.replace("/login"); }
  return <main className="min-h-dvh bg-slate-100 px-5 py-10 text-slate-950 dark:bg-slate-950 dark:text-slate-100"><section className="mx-auto w-full max-w-md rounded-[24px] border border-slate-200 bg-white p-7 shadow-xl shadow-slate-900/10 dark:border-slate-700 dark:bg-slate-900"><Image alt="DeliverEaze Logistics" className="mx-auto h-auto w-44" height={108} priority src="/images/brand/delivereaze-logo-light.webp" width={640} /><div className="mt-8"><p className="text-sm font-bold text-purple-600">Operations Portal</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em]">Verify your identity</h1><p className="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-400">Enter the six-digit code from your authenticator app.</p></div>{loading ? <p className="mt-6 text-sm text-slate-500">Loading authenticators...</p> : <div className="mt-6 space-y-4">{factors.length > 1 ? <label className="block text-sm font-semibold">Use another authenticator<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" onChange={(event) => setSelected(event.target.value)} value={selected}>{factors.map((factor, index) => <option key={factor.id} value={factor.id}>{factor.friendly_name || `Authenticator ${index + 1}`}</option>)}</select></label> : null}<label className="block text-sm font-semibold">Authenticator code<input autoComplete="one-time-code" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-lg tracking-[0.3em] dark:border-slate-700 dark:bg-slate-950" inputMode="numeric" maxLength={6} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} value={code} /></label>{error ? <p className="rounded-xl border border-red-100 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p> : null}<button className="h-11 w-full rounded-full bg-[#6d4aff] text-sm font-semibold text-white disabled:bg-purple-300" disabled={busy || !factors.length} onClick={() => void verify()} type="button">{busy ? "Verifying..." : "Verify"}</button></div>}<button className="mt-5 w-full text-sm font-semibold text-purple-700 disabled:text-slate-400" disabled={busy} onClick={() => void signOut()} type="button">Sign out</button></section></main>;
}

export default function VerifyMfaPage() { return <Suspense fallback={<main className="min-h-dvh bg-slate-100" />}><VerifyMfaPageContent /></Suspense>; }
