import {
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowsClockwiseIcon as ArrowsClockwise,
  ArrowsOutIcon as ArrowsOut,
  BellIcon as Bell,
  CalendarBlankIcon as CalendarBlank,
  CalendarDotsIcon as CalendarDots,
  CaretDownIcon as CaretDown,
  CaretLeftIcon as CaretLeft,
  CaretRightIcon as CaretRight,
  ChartBarIcon as ChartBar,
  CheckIcon as Check,
  CheckCircleIcon as CheckCircle,
  CheckSquareIcon as CheckSquare,
  ClipboardTextIcon as ClipboardText,
  CrosshairIcon as Crosshair,
  DotsThreeIcon as DotsThree,
  DownloadSimpleIcon as DownloadSimple,
  EnvelopeIcon as Envelope,
  EyeIcon as Eye,
  FileTextIcon as FileText,
  FlagIcon as Flag,
  FloppyDiskIcon as FloppyDisk,
  FunnelSimpleIcon as FunnelSimple,
  GaugeIcon as Gauge,
  GearIcon as Gear,
  IdentificationCardIcon as IdentificationCard,
  MagnifyingGlassIcon as MagnifyingGlass,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinus,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlus,
  MapPinIcon as MapPin,
  MapTrifoldIcon as MapTrifold,
  MinusIcon as Minus,
  NavigationArrowIcon as NavigationArrow,
  PackageIcon as Package,
  PathIcon as Path,
  PencilSimpleIcon as PencilSimple,
  PhoneIcon as Phone,
  PlusCircleIcon as PlusCircle,
  PlusIcon as Plus,
  PulseIcon as Activity,
  ReceiptIcon as Receipt,
  ShieldCheckIcon as ShieldCheck,
  SignOutIcon as SignOut,
  SlidersHorizontalIcon as SlidersHorizontal,
  SparkleIcon as Sparkle,
  SpinnerGapIcon as SpinnerGap,
  SquareIcon as Square,
  SquaresFourIcon as SquaresFour,
  StackIcon as Layers,
  TrashIcon as Trash,
  TruckIcon as Truck,
  UserCircleIcon as UserCircle,
  UserIcon as User,
  UsersIcon as Users,
  WalletIcon as Wallet,
  WarningIcon as Warning,
  WrenchIcon as Wrench,
  XCircleIcon as XCircle,
  XIcon as X,
} from "@phosphor-icons/react";

export const AppIcons = {
  dashboard: SquaresFour,
  users: Users,
  drivers: UserCircle,
  vehicles: Truck,
  schedules: CalendarDots,
  routes: Path,
  deliveries: Package,
  finance: Wallet,
  reports: ChartBar,
  settings: Gear,
  brand: Package,

  notifications: Bell,
  search: MagnifyingGlass,
  create: Plus,
  filter: SlidersHorizontal,
  funnel: FunnelSimple,
  view: Eye,
  edit: PencilSimple,
  delete: Trash,
  close: X,
  dropdown: CaretDown,
  previous: CaretLeft,
  next: CaretRight,
  back: ArrowLeft,
  forward: ArrowRight,
  more: DotsThree,
  logout: SignOut,
  phone: Phone,
  email: Envelope,
  location: MapPin,
  time: CalendarDots,
  clock: CalendarBlank,
  warning: Warning,
  completed: CheckCircle,
  check: Check,
  checkedSquare: CheckSquare,
  uncheckedSquare: Square,
  cancelled: XCircle,
  maintenance: Wrench,
  receipt: Receipt,
  export: DownloadSimple,
  refresh: ArrowsClockwise,
  navigation: NavigationArrow,
  map: MapTrifold,
  calendar: CalendarBlank,
  identification: IdentificationCard,
  mileage: Gauge,
  insurance: ShieldCheck,
  document: FileText,
  clipboard: ClipboardText,
  customer: User,
  priority: Flag,
  activity: Activity,
  save: FloppyDisk,
  addCircle: PlusCircle,
  minus: Minus,
  zoomIn: MagnifyingGlassPlus,
  zoomOut: MagnifyingGlassMinus,
  locate: Crosshair,
  fullscreen: ArrowsOut,
  layers: Layers,
  loading: SpinnerGap,
  optimize: Sparkle,
};

export type AppIconName = keyof typeof AppIcons;
